
// swift-tools-version:5.4
// The swift-tools-version declares the minimum version of Swift required to build this package.
// THIS FILE IS AUTOGENERATED

import PackageDescription

let package = Package(
    name: "bluejeans-ios-client-sdk",

    platforms: [
        .iOS(.v13)
    ],
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "bluejeans-ios-client-sdk",
            targets: ["bluejeans-ios-client-sdk"]),
        .library(
            name: "bluejeans-ios-client-sdk-simulator",
            targets: ["bluejeans-ios-client-sdk-simulator"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "bluejeans-ios-client-sdk",dependencies: [ "dvclient", "Reachability", "VZXRCVCommon", "VZXRCVVideoEffects", "VZXRCVFeatureVirtualBackgrounds", "BJNiOSBroadcastExtension", "BJNClientCore", "BJNClientBaseCore", "bjnmediacapturer", "PubNub", "BJNAPIClient", "Swinject", "SocketRocket", "fiberClient", "BJNHTTP", "koko", "fiber", "Mixpanel", "BJNiOSCore", "BJNClientSDK", "videoeffects", "MMWormhole", "CocoaLumberjackSwift", "CocoaLumberjack",]),        .target(
            name: "bluejeans-ios-client-sdk-simulator",dependencies: [ "dvclient", "Reachability", "BJNiOSBroadcastExtension", "BJNClientCore", "BJNClientBaseCore", "bjnmediacapturer", "PubNub", "BJNAPIClient", "Swinject", "SocketRocket", "fiberClient", "BJNHTTP", "koko", "fiber", "Mixpanel", "BJNiOSCore", "BJNClientSDK", "videoeffects", "MMWormhole", "CocoaLumberjackSwift", "CocoaLumberjack",]),        .binaryTarget(name: "dvclient", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/dvclient.zip", checksum: "616cc504229897b42507cefa0fcc1938b4bb3a9de25aa8e1a7cdfb5e8d5e9e76"),
        .binaryTarget(name: "Reachability", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/Reachability.zip", checksum: "795567bea7fa54640f18a11a16072383ed5e39efff4c2d07e59f308470d72113"),
        .binaryTarget(name: "VZXRCVCommon", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/VZXRCVCommon.zip", checksum: "d2dd60ac327db26c22fe90d679d0a2d3597ca914bbc7701e97a592b8c7f65fcc"),
        .binaryTarget(name: "VZXRCVVideoEffects", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/VZXRCVVideoEffects.zip", checksum: "0cc37b71ff3ea195aa3a3ca04aaba70905d3408f34a55ccaa92c097c6eea7a8a"),
        .binaryTarget(name: "VZXRCVFeatureVirtualBackgrounds", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/VZXRCVFeatureVirtualBackgrounds.zip", checksum: "12e4106f8bfb8b486e5276de3bd0ff397771e28e564dc4a2b24f1f16a4525842"),
        .binaryTarget(name: "BJNiOSBroadcastExtension", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/BJNiOSBroadcastExtension.zip", checksum: "09174d71ea4abd26a8f31005a7fa8b036ef113949b053831f8cef12e3039cecd"),
        .binaryTarget(name: "BJNClientCore", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/BJNClientCore.zip", checksum: "b84b5dd11b9a80efaf4625141fc19ed30d061fdaacdfcd6123b51fc86a2ada3a"),
        .binaryTarget(name: "BJNClientBaseCore", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/BJNClientBaseCore.zip", checksum: "133ea2aaec2cc0685968c48251c60ceb215c84a5ac6e14208356771d68ba2c80"),
        .binaryTarget(name: "bjnmediacapturer", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/bjnmediacapturer.zip", checksum: "4ee4084929b63aeea5b91016f274b0824383c61446d270bd56e2f6b23f4a6711"),
        .binaryTarget(name: "PubNub", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/PubNub.zip", checksum: "c8c1728d65282a4d4a9bcb7cb033ebcb5a64b207e59d33b305e025830776ecee"),
        .binaryTarget(name: "BJNAPIClient", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/BJNAPIClient.zip", checksum: "172c68b4a92561b84d387040b6967308362f960dfb48e63ba7a131f3e6351633"),
        .binaryTarget(name: "Swinject", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/Swinject.zip", checksum: "f9d1e93d5aeb2b381615fc3e147847b472acf24537887efda751f49f6a23025b"),
        .binaryTarget(name: "SocketRocket", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/SocketRocket.zip", checksum: "f28f8421e031840b7ea8192f4554f722ea7a2b7c5a57945162c23e1ce7e7302b"),
        .binaryTarget(name: "fiberClient", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/fiberClient.zip", checksum: "5fad83aacf8b093ce980e5f1131d69ec41a6b9a69dac2ef711a3dfe677d888b0"),
        .binaryTarget(name: "BJNHTTP", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/BJNHTTP.zip", checksum: "4ad400a27ad96e2d65394e5c8e8b6fd7a8f551515fd2285b135a2086cf311f9b"),
        .binaryTarget(name: "koko", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/koko.zip", checksum: "be74c45a3c28ee99154a5fdf46d4ea679571c43a502d41dd19c041d00b1c69a8"),
        .binaryTarget(name: "fiber", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/fiber.zip", checksum: "625d29aa5f272761d914023522c004d9fc0f5f674ab9363297463d6f94669877"),
        .binaryTarget(name: "Mixpanel", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/Mixpanel.zip", checksum: "13ca55e31320272696c33245bd25444708e9c3ec467bfcec175c4dce6bbd0ca5"),
        .binaryTarget(name: "BJNiOSCore", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/BJNiOSCore.zip", checksum: "70281eed4f21381aa26cd6d4b9dbb49830052c09bda88973b8e5117a20ea752b"),
        .binaryTarget(name: "BJNClientSDK", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/BJNClientSDK.zip", checksum: "c8c2dadfd35233f0301c8935a92389cb77b19315b1caa7bfe80bfc8882a3eaf0"),
        .binaryTarget(name: "videoeffects", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/videoeffects.zip", checksum: "63352f80faaa021e702d7434db265e33f6317bf1e40abc69643665a1b753da02"),
        .binaryTarget(name: "MMWormhole", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/MMWormhole.zip", checksum: "66bddcef1cdd65e7d7918d2b8ac29e4617e660dc775ac8748c623fd6d56ad6ac"),
        .binaryTarget(name: "CocoaLumberjackSwift", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/CocoaLumberjackSwift.zip", checksum: "14f0ce488a36ebc8bf5a57fc724c1487a79c09b2dcc2848d0e2fd949af4fdf31"),
        .binaryTarget(name: "CocoaLumberjack", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.4.0/SPM_Frameworks/CocoaLumberjack.zip", checksum: "fc068aa7dee8a7ae72ed65f2d03329166666c773c794321868810aa8d985c2b6"),    ]
)

