
// swift-tools-version:5.4
// The swift-tools-version declares the minimum version of Swift required to build this package.
// THIS FILE IS AUTOGENERATED

import PackageDescription

let package = Package(
    name: "bluejeans-ios-client-sdk",

    platforms: [
        .iOS(.v13)
    ],
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "bluejeans-ios-client-sdk",
            targets: ["bluejeans-ios-client-sdk"]),
        .library(
            name: "bluejeans-ios-client-sdk-simulator",
            targets: ["bluejeans-ios-client-sdk-simulator"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "bluejeans-ios-client-sdk",dependencies: [ "dvclient", "Reachability", "VZXRCVCommon", "VZXRCVVideoEffects", "VZXRCVFeatureVirtualBackgrounds", "BJNiOSBroadcastExtension", "BJNClientCore", "dvdnr", "BJNClientBaseCore", "bjnmediacapturer", "PubNubSpace", "PubNub", "BJNAPIClient", "Swinject", "SocketRocket", "fiberClient", "PubNubMembership", "BJNHTTP", "koko", "fiber", "Mixpanel", "BJNiOSCore", "PubNubUser", "BJNClientSDK", "videoeffects", "MMWormhole", "CocoaLumberjackSwift", "CocoaLumberjack",]),        .target(
            name: "bluejeans-ios-client-sdk-simulator",dependencies: [ "dvclient", "Reachability", "BJNiOSBroadcastExtension", "BJNClientCore", "dvdnr", "BJNClientBaseCore", "bjnmediacapturer", "PubNubSpace", "PubNub", "BJNAPIClient", "Swinject", "SocketRocket", "fiberClient", "PubNubMembership", "BJNHTTP", "koko", "fiber", "Mixpanel", "BJNiOSCore", "PubNubUser", "BJNClientSDK", "videoeffects", "MMWormhole", "CocoaLumberjackSwift", "CocoaLumberjack",]),        .binaryTarget(name: "dvclient", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/dvclient.zip", checksum: "a77fb82edb1ef204139405dd96342a63e009db4b537f1cf1c58d30e20be4ae55"),
        .binaryTarget(name: "Reachability", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/Reachability.zip", checksum: "48c8f080878e17e13185d546dafd814507fddce794b9a8304576b3d0044a3054"),
        .binaryTarget(name: "VZXRCVCommon", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/VZXRCVCommon.zip", checksum: "e7b15a132d2c843c967efadf1097578367b72c2b85a000035b8ab728f6803082"),
        .binaryTarget(name: "VZXRCVVideoEffects", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/VZXRCVVideoEffects.zip", checksum: "968d3fae0dda36bced110ab2d68224557289538ad0da984e197770accc0ac2f3"),
        .binaryTarget(name: "VZXRCVFeatureVirtualBackgrounds", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/VZXRCVFeatureVirtualBackgrounds.zip", checksum: "e1d95ea6b9bbbdfb0aecfbd4117018474f341bc2d24ba43644e3ca55c6b83bf6"),
        .binaryTarget(name: "BJNiOSBroadcastExtension", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/BJNiOSBroadcastExtension.zip", checksum: "9e346d2a16e18e8fa21abb34947d72af11a9a1ad5c4f942fda539c7382131af9"),
        .binaryTarget(name: "BJNClientCore", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/BJNClientCore.zip", checksum: "f822243efa0cd33dbcf6383928ffca9305fa956cbf077d38b658a684253f305f"),
        .binaryTarget(name: "dvdnr", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/dvdnr.zip", checksum: "fcd5ad04a8384d5d43f366f93c0b90ee9dba6329bb441de738a3abe5dbc67b57"),
        .binaryTarget(name: "BJNClientBaseCore", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/BJNClientBaseCore.zip", checksum: "b3d2463346d1ba9c9811169dbc6a35be6cf2305b85fe40a5b2b19da1c446f1b1"),
        .binaryTarget(name: "bjnmediacapturer", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/bjnmediacapturer.zip", checksum: "7f7b4f960fd192a66dc1acd9f9b9b53301fa0a0032bff7b73807134e161ba58e"),
        .binaryTarget(name: "PubNubSpace", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/PubNubSpace.zip", checksum: "e811a7d323d8bc2ca4f074137887745a29f730ac5cff176f37b34c51b26147a6"),
        .binaryTarget(name: "PubNub", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/PubNub.zip", checksum: "8dc762160ddd9f33e101ed9c976befddebebc47908a0df0b43ba3cd1d5341b6a"),
        .binaryTarget(name: "BJNAPIClient", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/BJNAPIClient.zip", checksum: "974620237a1b361e980604d26ec01156845cd653352fc84f7577aaaf7e326cc0"),
        .binaryTarget(name: "Swinject", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/Swinject.zip", checksum: "7a16074ecf9d7d046de255c1babea593f369499ff4360359945bd2ad1923aca1"),
        .binaryTarget(name: "SocketRocket", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/SocketRocket.zip", checksum: "293878f440fca7e214655d78c49da8476be77e4637f7e1a4ca0ec1cf033f1328"),
        .binaryTarget(name: "fiberClient", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/fiberClient.zip", checksum: "8dad6b817addd75201a9a3c7f57f96a669b6886a49a0588907e1b547a30ce66c"),
        .binaryTarget(name: "PubNubMembership", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/PubNubMembership.zip", checksum: "25bdb7d26c38d2f6b29a7ca9e1a3b4b8aa657d55a5b348b0dd1f7b4c6eeb7912"),
        .binaryTarget(name: "BJNHTTP", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/BJNHTTP.zip", checksum: "c228e498f72f3e52f420fd45b95bc8c15d9b8f2eef04cd2a312c353dfa382810"),
        .binaryTarget(name: "koko", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/koko.zip", checksum: "c31938c764cfc9dc05e1dbbd8d49257af6f333296b3bd04727234dc220221536"),
        .binaryTarget(name: "fiber", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/fiber.zip", checksum: "5bc485b619f56962ad0d78445fa21b58825ae8540f64bbe5bed6307cba008c6e"),
        .binaryTarget(name: "Mixpanel", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/Mixpanel.zip", checksum: "ee8fd2db9cbe7a264be8eb4c686978a8f0dac50e201f052f49e1ec80d02e358d"),
        .binaryTarget(name: "BJNiOSCore", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/BJNiOSCore.zip", checksum: "8a4bd7e0f32992d5411dd08d829ff55b475fdfe05d12b8f312f3a5a86aa7a967"),
        .binaryTarget(name: "PubNubUser", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/PubNubUser.zip", checksum: "30854ecf14e9806da63ee0b5750e704c714b88b6a9261eb6fcc1f85cffd7ffaf"),
        .binaryTarget(name: "BJNClientSDK", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/BJNClientSDK.zip", checksum: "007a82ca2e01bed860d9927b35c79282b855284aa0349d14549c118e77507091"),
        .binaryTarget(name: "videoeffects", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/videoeffects.zip", checksum: "eec5fe7fbb6cc36af06b90b784846dbde7772cc8baf459c2ee38d309996507a4"),
        .binaryTarget(name: "MMWormhole", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/MMWormhole.zip", checksum: "e0b8e1520314b55b032be342aef15f7cef3ad09dde55dc523df12ca200271172"),
        .binaryTarget(name: "CocoaLumberjackSwift", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/CocoaLumberjackSwift.zip", checksum: "e76b5c1f313b5cac6129b096ea0e3b439efedd859f59ac605a2105256a95a47a"),
        .binaryTarget(name: "CocoaLumberjack", url: "https://swdl.bluejeans.com/bjnvideosdk/ios/1.7.0/SPM_Frameworks/CocoaLumberjack.zip", checksum: "509bc18365f59f5d56dd1558de2ab575521c1a70aac791a93741fe7c2765d28d"),    ]
)

